trigger:
  branches:
    include:
    - v4-master

resources:
- repo: self

jobs:
- job: windows_release
  pool:
    vmImage: 'vs2015-win2012r2'

  steps:
  - task: CmdLine@2
    inputs:
      script: 'git checkout v4-master'
  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)\scripts\build-windows\build.ps1'
      arguments: 'quick -Platform x64 -SpecificVisualStudioVersion 2015 -Configuration release -Version ($env:SemanticVersion)'