trigger:
  branches:
    include:
    - v4-master

resources:
- repo: self

jobs:
- job: windows_release
  pool:
    vmImage: 'windows-2019'

  steps:
  - task: CmdLine@2
    inputs:
      script: 'git checkout v4-master'
  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)\scripts\build-windows\build.ps1'
      arguments: 'quick -Platform x64 -SpecificVisualStudioVersion 2019 -Configuration release -Version ($env:SemanticVersion)'