trigger:
- v4-master

resources:
- repo: self

jobs:
- job: windows_release
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - task: CmdLine@2
      inputs:
        script: '.\build.cmd quick -Platform x64  -Configuration release -Version ($env:SemanticVersion)'