trigger:
- v4-master

resources:
- repo: self

jobs:
- job: windows_release
  pool:
    vmImage: 'windows-2019'

  steps:
  - task: PowerShell@2
    inputs:
      filePath: './scripts/build-windows/build.ps1'
      arguments: 'quick -Platform x64 -SpecificVisualStudioVersion 2019 -Configuration release -Version ($env:SemanticVersion)'