trigger:
- v4-master

resources:
- repo: self

jobs:
- job: windows_release
  pool:
    vmImage: 'windows-2019'

  steps:
    - task: CmdLine@2
      inputs:
        script: '.\build.cmd quick -Platform x64 -SpecificVisualStudioVersion 2015 -Configuration release -Version ($env:SemanticVersion)'